# Basic Information 
title: Daniel Sungho Jung
position: Ph.D. Candidate
affiliation: Seoul National University
affiliation_link: https://www.snu.ac.kr/index.html
affiliation_logo: /assets/img/snu_logo.svg
email: dqj5182@snu.edu

# Search Engine Optimization (SEO)
keywords: daniel jung, daniel, daniel sungho jung, sungho jung
canonical: https://dqj5182.github.io
description: Daniel Sungho Jung is a Ph.D. Candidate at SNU. His research lies in 3D human reconstruction and 3D scene reconstruction.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=NLU-rPkAAAAJ&hl=en
github_link: https://github.com/dqj5182
linkedin: https://www.linkedin.com/in/danieljung0121/
twitter: https://x.com/dqj5182

# Images 
avatar: https://dqj5182.github.io/assets/img/profile.jpeg
favicon: /assets/img/snu_logo.ico
favicon_dark: /assets/img/snu_logo.ico

# Footnotes
footnote: If you want source code, please refer to prof. liu's webpage.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
